# Enable or disable the plugin
enabled: true

# Enable or disable the log
enable-logging: true

# Logging level: INFO, DEBUG
logging-level: "INFO"


# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------


# List of worlds where the plugin is disabled
disabled-worlds: [ ]

# List of materials that are not allowed to be disenchanted
disabled-materials: [ ]

# List of enchantments status for item disenchantment.
enchantments-status:
  # Here is example of how it should look like.
  # enchantments can take value "enabled", "keep" and "disabled"
  sharpness: enabled


# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------


# Enable or disable the book splitting
disable-book-splitting: false

# List of worlds where the book splitting is disabled
disabled-book-splitting-worlds: [ ]

# List of enchantments status for book splitting
book-splitting-enchantments-status:
  # Here is example of how it should look like.
  # enchantments can take value "enabled", "keep" and "disabled"
  sharpness: enabled


# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------


# Enable or disable the anvil sound
enable-anvil-sound: true

# Edit the volume and pitch of the anvil sound
anvil-volume: 1.0
anvil-pitch: 1.0


# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------


# Enable or disable the repair cost reset back to 0 when the item is disenchanted
enable-repair-reset: false

# Enable or disable the repair cost
enable-repair-cost: true

# Base value for the cost of the disenchantment
base: 10

# This multiplication is applied to the base value
# The enchantments are sorted by level in descending order, so the more enchantments you have, the more expensive it is
# Multiplication value from 0 to infinity (0.25 = 25%)
# ---
# It is calculated by the following:
#   base + (level * multiply)
# ---
# Example: base = 10, sharpness = 5, knockback = 1, multiplier = 0.25
#
#   10 + (1 * 1) = 11  ->  11 + (5 * 1.25) = 17.25  ->  17.25
#
multiply: 0.25
