name: Disenchantment
version: '5.1.1'
main: cz.kominekjan.disenchantment.Disenchantment
api-version: '1.20.6'
authors:
  - Jan Komínek
description: Allows players to disenchant items and get the item's enchantments back
website: 'https://kominekjan.cz'
softdepend: [ ExcellentEnchants, EcoEnchants, eco, AdvancedEnchantments, UberEnchant, EnchantsSquared ]
commands:
  disenchantment:
    description: 'Disenchantment command'
    aliases:
      - disenchantment
      - disenchant
      - disench
    usage: '/<command>'
    permission: disenchantment.use
    permission-message: You don't have permission to use this command.
permissions:
  disenchantment.all:
    description: Access to all permissions
    default: op
  disenchantment.anvil:
    description: Allows the player to disenchant items
    default: op
  disenchantment.command.gui:
    description: GUI command
    default: op
  disenchantment.command.help:
    description: Help command
    default: op
  disenchantment.command.status:
    description: Status command
    default: op
  disenchantment.command.toggle:
    description: Toggle command
    default: op
  disenchantment.command.repair:
    description: Repair command
    default: op
  disenchantment.command.enchantments:
    description: Enchantments command
    default: op
  disenchantment.command.materials:
    description: Materials command
    default: op
  disenchantment.command.sound:
    description: Sound command
    default: op
  disenchantment.gui.status:
    description: GUI Enable or disable the plugin
    default: op
  disenchantment.gui.toggle:
    description: GUI Enable or disable the plugin in a specific world
    default: op
  disenchantment.gui.repair:
    description: GUI Set the repair settings
    default: op
  disenchantment.gui.enchantments:
    description: GUI Set the enchantments settings
    default: op
  disenchantment.gui.materials:
    description: GUI Set the materials settings
    default: op
  disenchantment.gui.sound:
    description: GUI Set the sound settings
    default: op
