name: Disenchantment
version: '4.1.0'
main: cz.kominekjan.disenchantment.Disenchantment
api-version: '1.20.6'
authors:
  - HonzaKOMI
description: Don't lose your enchantments!
website: 'https://kominekjan.cz'
softdepend: [ ExcellentEnchants, EcoEnchants, eco, AdvancedEnchantments ]
commands:
  disenchantment:
    description: 'Disenchantment command.'
    aliases:
      - disenchantment
      - disenchant
      - disench
    usage: '/<command>'
    permission: disenchantment.use
    permission-message: You don't have permission to use this command.
permissions:
  disenchantment.anvil:
    description: Allows you to use disenchant in an anvil.
    default: op
  disenchantment.use:
    description: Allows you to use the disenchantment command.
    default: op
  disenchantment.toggle:
    description: Allows you to toggle disenchantment. And also disable specific worlds.
    default: op
  disenchantment.status:
    description: Allows you to check if disenchantment is on/off.
    default: op
  disenchantment.repair:
    description: Allows you to configure disenchantment repair.
    default: op
  disenchantment.sound:
    description: Allows you to configure disenchantment sound.
    default: op
  disenchantment.enchantments:
    description: Allows you to configure disenchantment enchantments.
    default: op
  disenchantment.materials:
    description: Allows you to configure disenchantment materials.
    default: op
  disenchantment.help:
    description: Allows you to check disenchantment help.
    default: op
