name: Disenchantment
version: '5.4.0'
main: cz.kominekjan.disenchantment.Disenchantment
api-version: '1.21.1'
authors:
  - Jan Komínek
description: Allows players to disenchant items and get the item's enchantments back
website: 'https://kominekjan.cz'
softdepend: [ ExcellentEnchants, EcoEnchants, eco, AdvancedEnchantments, UberEnchant, EnchantsSquared ]
commands:
  disenchantment:
    description: 'Disenchantment command'
    aliases:
      - disenchantment
      - disenchant
      - disench
      - shatterment
    usage: '/<command>'
    permission: disenchantment.use
    permission-message: You don't have permission to use this command.
permissions:
  disenchantment.all:
    description: Access to all permissions
    default: op
  disenchantment.anvil:
    description: Allows the player to disenchant items or shatter books
    default: op
  disenchantment.anvil.disenchant:
    description: Allows the player to disenchant items
    default: op
  disenchantment.anvil.shatter:
    description: Allows the player to split enchantments from books
    default: op
  disenchantment.command.gui:
    description: GUI command
    default: op
  disenchantment.command.help:
    description: Help command
    default: op
  disenchantment.command.status:
    description: Status command
    default: op
  disenchantment.command.toggle:
    description: Toggle command
    default: op
  disenchantment.command.disenchantment_repair:
    description: Repair command
    default: op
  disenchantment.command.disenchantment_enchantments:
    description: Enchantments command
    default: op
  disenchantment.command.disenchantment_materials:
    description: Materials command
    default: op
  disenchantment.command.disenchantment_sound:
    description: Sound command
    default: op
  disenchantment.command.shatterment_repair:
    description: Repair command
    default: op
  disenchantment.command.shatterment_enchantments:
    description: Enchantments command
    default: op
  disenchantment.command.shatterment_materials:
    description: Materials command
    default: op
  disenchantment.command.shatterment_sound:
    description: Sound command
    default: op
  disenchantment.gui.status:
    description: GUI Enable or disable the plugin
    default: op
  disenchantment.gui.toggle:
    description: GUI Enable or disable the plugin in a specific world
    default: op
  disenchantment.gui.disenchantment_repair:
    description: GUI Set the repair settings
    default: op
  disenchantment.gui.disenchantment_enchantments:
    description: GUI Set the enchantments settings
    default: op
  disenchantment.gui.disenchantment_materials:
    description: GUI Set the materials settings
    default: op
  disenchantment.gui.disenchantment_sound:
    description: GUI Set the sound settings
    default: op
  disenchantment.gui.shatterment_repair:
    description: GUI Set the repair settings
    default: op
  disenchantment.gui.shatterment_enchantments:
    description: GUI Set the enchantments settings
    default: op
  disenchantment.gui.shatterment_materials:
    description: GUI Set the materials settings
    default: op
  disenchantment.gui.shatterment_sound:
    description: GUI Set the sound settings
    default: op
