name: Disenchantment
version: 6.1.4
main: com.jankominek.disenchantment.Disenchantment
api-version: 1.18

author: Jan Komínek
website: https://github.com/H7KZ/Disenchantment

softdepend: [ ExcellentEnchants, EcoEnchants, eco, AdvancedEnchantments, UberEnchant, EnchantsSquared ]

commands:
  disenchantment:
    description: 'Disenchantment command'
    aliases:
      - disenchantment
      - disenchant
    usage: '/<command>'
    permission: disenchantment.command.use
    permission-message: You don't have permission to use this command.

permissions:
  disenchantment.all:
    description: Access to everything/all permissions.
    default: op
  disenchantment.anvil.all:
    description: Allows the player to disenchant items or shatter books.
    default: op
  disenchantment.anvil.disenchant:
    description: Allows the player to disenchant items.
    default: op
  disenchantment.anvil.shatter:
    description: Allows the player to split enchantments from books.
    default: op
  disenchantment.command.use:
    description: Access to the disenchantment command.
    default: op
  disenchantment.command.all:
    description: Access to every command.
    default: op
  disenchantment.command.gui:
    description: Access to the gui command.
    default: op
  disenchantment.command.help:
    description: Access to the help command.
    default: op
  disenchantment.command.status:
    description: Access to the status command.
    default: op
  disenchantment.command.toggle:
    description: Access to the toggle command.
    default: op
  disenchantment.command.disenchant.enchantments:
    description: Access to the disenchant enchantments command.
    default: op
  disenchantment.command.disenchant.worlds:
    description: Access to the disenchant worlds command.
    default: op
  disenchantment.command.disenchant.materials:
    description: Access to the disenchant materials command.
    default: op
  disenchantment.command.disenchant.repair:
    description: Access to the disenchant repair command.
    default: op
  disenchantment.command.disenchant.sound:
    description: Access to the disenchant sound command.
    default: op
  disenchantment.command.shatter.enchantments:
    description: Access to the shatter enchantments command.
    default: op
  disenchantment.command.shatter.worlds:
    description: Access to the shatter worlds command.
    default: op
  disenchantment.command.shatter.repair:
    description: Access to the shatter repair command.
    default: op
  disenchantment.command.shatter.sound:
    description: Access to the shatter sound command.
    default: op
  disenchantment.gui:
    description: Allows the player to open the GUI.
    default: op
  disenchantment.gui.all:
    description: Allows the player to access all GUI settings.
    default: op
  disenchantment.gui.status:
    description: Allows the player to see the status of the plugin.
    default: op
  disenchantment.gui.worlds:
    description: Allows the player to set the anvil worlds.
    default: op
  disenchantment.gui.enchantments:
    description: Allows the player to set the anvil enchantments.
    default: op
  disenchantment.gui.materials:
    description: Allows the player to set the anvil materials.
    default: op
  disenchantment.gui.disenchant.repair:
    description: Allows the player to set the disenchant repair settings.
    default: op
  disenchantment.gui.disenchant.sound:
    description: Allows the player to set the disenchant sound settings.
    default: op
  disenchantment.gui.shatter.repair:
    description: Allows the player to set the shatter repair settings.
    default: op
  disenchantment.gui.shatter.sound:
    description: Allows the player to set the shatter sound settings.
    default: op
